= III / La légitimation des contenus

== Les modèles « classiques »

=== La reconnaissance symbolique de l’édition papier

De quelle manière peut-on donner de la crédibilité à un contenu ? Comment faire
en sorte qu’un texte, un document, une information soient considérés comme fiables ?
Comment donner de l’autorité à des affirmations ou à des idées ? Voici quelques unes des
questions fondamentales auxquelles doit répondre aujourd’hui la fonction éditoriale.
Comme on l’a vu, les maisons d’édition comptent, au moins depuis le XVIIIe siècle,
parmi les instances qui remplissent la fonction de légitimation. La légitimité du contenu
est fonction de la légitimité symbolique de la maison d’édition qui le publie. Mais
comment une maison d’édition peut-elle concrètement être source de légitimation ? Pour
répondre à cette question, on peut identifier trois différents types de légitimation : le
prestige, la visibilité et l’évaluation scientifique.

. Le prestige dépend de la réputation qu’une maison d’édition a pu acquérir auprès
des lecteurs. Ces derniers connaissent le nom de la maison et associent à ce nom une
idée de qualité. Cette valeur symbolique est transférée de la maison d’édition aux
ouvrages qu’elle publie. Concrètement, le nom et le logo de la maison confèrent du
prestige à l’ouvrage et garantissent sa qualité. Ce type de légitimation est typique
des contenus destinés au grand public.
. La visibilité dépend de la capacité à faire connaître l’existence d’un contenu à un
certain nombre de personnes. Les maisons d’édition ont la possibilité de
communiquer sur leurs publications et de les rendre visibles. Si cette visibilité ne
garantit pas nécessairement la qualité de l’ouvrage, elle participe tout de même de sa
légitimation, car elle en détermine l’influence. Dans cette production de visibilité,
plusieurs maillons de la chaîne de valorisation du livre peuvent jouer un rôle
fondamental, comme les prix littéraires, qui augmentent l’audience des ouvrages et
se présentent comme un gage de qualité.
. L’évaluation scientifique concerne seulement un type particulier de contenus : ceux
destinés à un public de spécialistes – notamment d’universitaires –, souvent publiés
par des maisons d’édition spécialisées – comme des presses universitaires – ou dans
des collections particulières. Chaque ouvrage est en général soumis, avant
publication, à un processus d’évaluation par les pairs : la qualité et la rigueur
scientifique du contenu sont analysés et appréciés, souvent en aveugle, par des
spécialistes. Ce processus garantit la légitimité de l’ouvrage. Dans ce cas, la maison
d’édition est le garant du bon déroulement du processus d’évaluation, les spécialistes
auxquels est demandée l’évaluation étant extérieurs à la maison.

Un contenu peut bénéficier de ces trois types de légitimation en même temps : avoir
du prestige, de la visibilité et être garanti par une évaluation scientifique. Souvent, ces
aspects sont liés : la visibilité peut dépendre du prestige, le prestige du sérieux de
l’évaluation scientifique, etc. Mais ces types de légitimation peuvent aussi jouer de
manière isolée : on peut prendre l’exemple d’une petite maison d’édition universitaire, à
la visibilité très réduite et au prestige parfois limité, ou d’une grande maison d’édition
commerciale, se donnant les ventes pour seul objectif, et misant tout sur la visibilité.
Les environnements numériques ont indéniablement produit de nouveaux modèles
de légitimation. Ils ont ainsi, en partie, remis en question le monopole que les maisons
d’édition avaient conservé pendant plusieurs siècles en matière de légitimation. Mais il
serait faux d’affirmer que le numérique a enlevé – ou même affaibli – le pouvoir de
légitimation et la valeur symbolique des maisons d’édition. Le fait d’être édité par l’une
d’entre elles – en papier ou en format numérique – reste la source principale de légitimité
pour un contenu, même si ce n’est plus la seule.

=== L’auteur se porte bien

Une autre forme de légitimation d’un contenu provient de son auteur – ou, très
concrètement, du nom de l’auteur affiché sur la couverture d’un livre.
On peut identifier trois éléments propres à la fonction auctoriale en partie croisés
avec ceux de la fonction éditoriale. Tel qu’elle s’est stabilisée à partir du XVIIIe siècle, la
fonction auctoriale implique la propriété, l’originalité et enfin l’autorité [Rose, 1993].

. l’auteur a tout d’abord un certain droit de propriété sur ce qu’il produit. Cette notion
s’est affirmée et institutionnalisée à partir du XVIIIe siècle (le Statut d’Anne de 1710
est considéré, on l’a vu, comme la première loi sur le copyright). L’idée de lier
l’auctorialité à la propriété a rendu théoriquement possible la naissance de l’édition
papier telle que nous la connaissons. Le fait que l’auteur soit propriétaire du contenu
– et non du support qui le fait circuler – lui permet de vendre le droit d’exploitation
de son bien, notamment à une maison d’édition. Ce principe est à la base du modèle
économique de l’édition papier.
. En second lieu, l’auteur exprime un point de vue particulier et original, car il
manifeste, dans ses productions, son individualité. Les notions d’individu et
d’originalité deviennent essentielles pour expliquer la propriété intellectuelle :
l’auteur est propriétaire du fruit de son originalité, à savoir de ce qu’il est le seul à
pouvoir produire. La fonction auctoriale garantit donc aussi la reconnaissance de
l’auteur, son style, sa « marque ».
. En dernier lieu, l’auteur légitime et garantit les contenus qu’il produit. Il en est donc
aussi le responsable – y compris d’un point de vue légal. Cette fonction est
justement partagée avec l’éditeur, qui augmente et encadre la légitimité de l’auteur.
Les deux fonctions de légitimation – auctoriale et éditoriale – sont alors entremêlées.
Dans certains cas, l’une prévaut sur l’autre : par exemple, un auteur encore inconnu
verra sa légitimité garantie par la fonction éditoriale ; à l’inverse, un auteur très
connu pourra faire profiter de sa légitimité à un nouvel éditeur.

Qu’en est-il de ces structures dans les environnements numériques ? Depuis
quelques années, on entend souvent parler d’une crise de l’auteur. Cette crise est
indéniable, mais il serait faux de l’assimiler à une disparition de la fonction auctoriale. La
crise est due à la convergence d’une théorie critique du modèle de l’auteur que l’on vient
de décrire et de l’émergence de pratiques en environnement numérique qui mettent en
question l’unicité de ce modèle. À partir des années 1960, en effet, des théoriciens
comme Roland Barthes et Michel Foucault ont annoncé la « mort de l’auteur ». Leur
objectif était d’attaquer la notion romantique de l’auteur-créateur, du génie produisant à
partir de rien, dans l’originalité absolue. À ce modèle s’oppose une idée de la circulation
des textes et des idées qui ne relève jamais d’un individu isolé, mais d’une série
complexe de dynamiques culturelles, sociales et politiques. Ce n’est pas l’auteur qui
produit à partir de rien des contenus, ce sont les interactions sociales et culturelles qui les
font émerger. Or le Web – et en particulier le Web 2.0 – a permis l’émergence de
pratiques qui vont tout à fait dans ce sens : le nom de l’auteur s’efface au profit d’une
écriture collective, la signature de l’auteur devenant moins importante que celle de la
plate-forme. Les affirmations « j’ai lu cela sur Internet » ou « je l’ai trouvé sur Google »
sont à cet égard bien plus significatives qu’on pourrait le croire.

Or, s’il est vrai que de nouveaux modèles de légitimation sont en train d’émerger, il
n’en reste pas moins que la fonction auctoriale conserve son rôle de légitimation. Les
environnements numériques sont caractérisés par une hybridation de formes
traditionnelles et de formes classiques. Prenons l’exemple des blogs. Comme l’a
démontré Dominique Cardon [2010], un blogueur peut devoir sa réputation à la
popularité de son blog – et dans ce cas c’est le blog qui légitime l’auteur –, mais l’inverse
est aussi vrai : un blog peut être lu car le blogueur est déjà connu en tant qu’auteur. Ce
type de phénomène est très courant dans les environnements numériques, où les auteurs
peuvent démultiplier leur visibilité et donc leur autorité. S’il y a bel et bien une certaine
crise du concept d’auteur liée à l’émergence de nouveaux modèles de production et de
légitimation de contenus, l’auteur et la fonction auctoriale n’en ont pas pour autant perdu
leur propre pouvoir de légitimation.

=== La reconnaissance par le commerce

Dans les mécanismes de légitimation des contenus, la légitimation commerciale
occupe une place particulière. Par légitimation commerciale nous entendons l’ensemble
des logiques de légitimation s’appuyant sur des indicateurs de vente mais également les
logiques symboliques associées à des acteurs commerciaux. Cet aspect a été abordé
précédemment dans la reconnaissance symbolique de l’édition papier, mais nous
l’abordons ici sous l’angle des acteurs de la commercialisation, et notamment des
librairies.

Considérons tout d’abord la logique de légitimation par les chiffres de vente. Cette
logique est bien connue de l’ensemble des acteurs des industries culturelles, édition –
numérique ou non – comprise : dans un premier temps, un produit culturel, en raison de
sa qualité, de la communication, de l’actualité ou d’autres paramètres connait un certain
succès commercial. Il apparaît de ce fait dans des palmarès de vente qui peuvent jouer un
rôle, pour une partie du public, de recommandation. Cette visibilité renforcée induira des
ventes supplémentaires et améliorera la place dans les classements (ou par exemple sur
les tables des meilleures ventes de certaines librairies). Ces volumes de vente deviennent
parfois eux-mêmes des arguments commerciaux (« Déjà n exemplaires vendus ! »). Cette
mécanique est dans un deuxième temps contrariée par une saturation des publics visés ou
l’arrivée d’un nouveau titre profitant d’une dynamique semblable

L’édition numérique modifie cependant ce fonctionnement pour deux raisons :
l’émergence d’indicateurs non commerciaux (réputation, visibilité…) et le rôle
considérable des classements de ventes dans les pratiques d’achat sur les plates-formes de
vente en ligne. L’environnement numérique permet en effet une multiplicité de modalités
commerciales, de la vente classique de fichiers numériques ou de droits d’accès à la
rémunération par la publicité, en passant par les modèles freemium (contenu gratuit et
services payants). Cette multiplicité de modèles empêche de s’appuyer sur un seul type
de données commerciales pour établir des classements pertinents. Ce sont ainsi les
moteurs de recherche qui, via leurs algorithmes, agglomèrent les données les plus
diverses et proposent aux utilisateurs les classements les plus pertinents, dans lesquels les
ventes réalisées ou les droits d’accès vendus ne représentent qu’un aspect parmi d’autres.
Les stratégies d’optimisation de référencement de l’édition numérique se rapprochent
alors des stratégies de construction de réputation généralement utilisées pour les sites
Web.

À un second niveau, celui des classements sur les sites de vente, l’édition
numérique est confrontée à une problématique nouvelle. En effet, comme dans
l’ensemble des industries culturelles numériques, les plates-formes de vente occupent une
place croissante dans les vente de l’édition numérique, comme la place prépondérante
d’Amazon sur ce marché dans de nombreux pays le montre. Or, ces plates-formes
présentent, entre autres, deux caractéristiques qui modifient la place des données
commerciales dans les mécanismes de légitimation : le très grand nombre de titres
proposés, largement supérieur à toutes les offres existantes, et l’absence de
recommandation non algorithmique. Ces deux éléments concourent à l’exploitation
renforcée par les plates-formes de vente des classements fondés sur les ventes comme
outils de recommandation automatisés.

Cet enjeu des classements associé à la souplesse permise par le numérique dans
l’évolution du prix de vente a conduit au développement de stratégies de prix et de choix
de catégorisation des titres qui visent à faire rentrer des ouvrages dans les classements en
utilisant des prix bas et en choisissant des catégories moins concurrentielles que d’autres.
Une fois le titre entré dans le classement des meilleures ventes d’une catégorie, sa
notoriété croissante permet de faire remonter les prix pour retrouver un niveau de
rentabilité satisfaisant. Ces tactiques sont évidemment risquées, les titres n’atteignant pas
un niveau de vente suffisant demeurant à la fois moins visibles et moins rentables.

=== Le rôle des bibliothèques

Les bibliothèques, du fait de leur poids symbolique important, peuvent jouer un
rôle dans les logiques de légitimation des contenus. Pour l’édition papier, l’acquisition
par les bibliothèques peut conférer une légitimité ou une reconnaissance à des titres
parfois peu présents dans les circuits commerciaux habituels. Pour l’édition numérique
cette légitimité bibliothéconomique s’exerce de plusieurs façons.

L’édition numérique ouvre deux nouvelles voies de légitimation par les
bibliothèques. La première passe par le repérage, voire l’intégration dans leurs catalogues
et portails, d’ouvrages numériques librement accessibles en ligne. Cette démarche joue
un rôle de légitimation différent selon les ouvrages concernés. Pour les classiques, déjà
largement référencés, il ne s’agit pas d’une légitimation des oeuvres – qui n’en n’ont pas
besoin – mais du travail d’édition numérique réalisé sur les textes et fichiers. Pour
d’autres types ouvrages proposés librement en ligne, la présence sur le portail ou le
catalogue d’une bibliothèque confère de fait une légitimité, ne serait-ce que d’avoir été
considéré et sélectionné par les bibliothécaires. L’autre voie de légitimation par des
bibliothèques passe par l’organisation par ces dernières d’activités et d’ateliers de
création ou d’écriture. Cette approche, déjà mise en oeuvre dans des bibliothèques
publiques américaines, consiste à considérer le public comme producteur de contenus qui
viendront potentiellement enrichir le fonds. Cette démarche s’inscrit dans une dynamique
plus large à la croisée des modes de production (fablab, maker spaces…) et de
l’implication des publics dans la production de connaissances. Il s’agira par exemple
d’ateliers visant à recueillir les récits de vies d’habitants du quartier d’une bibliothèque,
récits qui viendront enrichir la documentation déjà proposée.

Dans ces deux cas, l’enjeu pour la bibliothèque est de se positionner par rapport à la
question de la légitimation. En reconnaissant certains contenus (issus de ses publics ou du
Web), elle joue un rôle qui la rapproche d’un éditeur. En effet, de la même façon qu’un
éditeur légitime un contenu éditorial en acceptant de le publier sous son nom, la
bibliothèque joue un rôle éditorial en acceptant de faire figurer dans ses espaces
numériques des contenus pas forcément issus d’une chaîne de production éditoriale
traditionnelle. Ces démarches s’accompagnent de plusieurs questionnements notamment
sur la légitimité professionnelle des bibliothécaires en matière d’édition, mais également
sur la neutralité des acteurs publics dans ce type de processus.
