==== Tableau 6. Les algorithmes et moteurs de recherche du Web
[cols="10,10,10,70"]
|===
| *Nom* | *Propriétaire* | *Créateurs (date de création)* | *Description*
|Yahoo! Search | Yahoo inc. | (1995) | À ses débuts, Yahoo! Search est moins un moteur de recherche
algorithmique qu’un annuaire web animé par l’ambition d’un classement
humain, manuel, du Web. À partir de 2000, Yahoo! Search est alimenté par
le moteur de recherche d’Inktomi, société rachetée par Yahoo en 2002, puis
par celui de Google jusqu’en 2004, date à laquelle Yahoo commence à
utiliser son propre algorithme. Cependant, depuis 2009, Yahoo est de
nouveau alimenté par un fournisseur externe, Microsoft Bing.
| PageRank | Google | Larry Page et Sergueï Brin (1996) | L’algorithme célèbre du moteur de recherche de Google, fondé sur un
principe méritocratique de réputation des sites web. S’inspirant du Science
Citation Index d’Eugène Garfield (1964), il mesure en l’autorité d’un site
web en calculant les liens entrants comme des votes, ces votes ayant plus
de poids lorsqu’ils proviennent eux-mêmes d’un site réputé.
| Hilltop Algorithm | Google (rachat en février 2003)| Krishna Bharat et George A. Mihăilă (1999) | Développé à l’Université de Toronto en 1999, l’algorithme Hilltop cherche
à identifier les résultats les plus pertinents lorsqu’un internaute effectue une
recherche vaste (ou peu détaillée) en attribuant une valeur d’autorité aux
pages web. Le classement du Hilltop est réalisé au moyen d’un index de
« documents d’experts », qui sont des pages web identifiées comme
expertes sur un certain sujet. Plus les relations hypertextuelles entre une
page web et sa page experte associée sont proches, plus la page en question
sera qualifiée d’autoritaire (« _authoritative_ »). L’algorithme Hilltop est
utilisé par Google depuis 2003.
| HITS Algoritm |  | Jon Kleinberg (1999) | L’algorithme HITS (Hyperlink-induced topic search) classe les pages web
en leur attribuant deux scores définis par récursion mutuelle : 1) leur valeur
de référenciation (_hub value_), qui équivaut à la valeur de leurs liens
renvoyant vers d’autres pages ; 2) leur valeur d’autorité (_authority value_),
qui correspond à la valeur du contenu de la page, calculée par la somme des
hub values des liens entrants. L’article de Kleinberg dans lequel il esquisse
le fonctionnement du HITS constituera une source d’influence pour Page et
Brin dans la conception du PageRank.
| TrustRank |   | Hector Garcia-Molina, Zoltán Gyöngyi et Jan Pedersen (2004)| Exposé lors d’une conférence de la Very Large Data Bases Endowment
Inc. à Toronto, TrustRank est une technique d’analyse semi-automatique
des liens visant à distinguer les pages web pertinentes des pages employant
une stratégie de spam de mots-clés et de liens sortants. En ce sens, le
TrustRank s’inscrit dans la même lignée que le PageRank en ce qu’il utilise
le réseau des liens comme mesure de qualité des pages web, mais la
nécessité d’un contrôle humain de l’algorithme vise à combattre avec
davantage de précision certaines tactiques du Search Engine Optimization
(SEO ou « optimisation pour les moteurs de recherche », désignant les
techniques d’optimisation de l’indexation et du référencement).
| Bing | Microsoft | (2009) | Bing est l’aboutissement d’une longue succession de moteurs de recherche
créés par Microsoft, à savoir MSN Search (1998), Windows Live Search
(2006) et Live Search (2007). Peu d’informations sur l’algorithme de Bing
sont rendues publiques, mais Microsoft a été accusé en 2010 de copier les
résultats de recherche de Google.
| EdgeRank | Facebook | Serkan Piantino (v. 2010) | Succédant à _Turning Knobs_, l’algorithme qui avait accompagné
l’introduction du _News Feed_ en 2006, EdgeRank procède à une
hiérarchisation des informations selon une métrique d’affinités. Chaque
fois qu’un utilisateur interragit sur Facebook, il produit un _edge_ qui reçoit
ensuite un score calculé à partir de trois variables : 1) Ue, ou la proximité
relationnelle entre l’utilisateur-acteur et l’utilisateur-lecteur (le score
d’affinité), elle-même déterminée par une série de paramètres (fréquence
de visite du profil, fréquence des conversations entretenues sur le site,
etc.) ; 2) We, qui correspond au poids de l’_edge_, c’est-à-dire à la nature
même de l’action de l’utilisateur (publication, _like_, commentaires, partage,
etc.) ; 3) De, le vieillissement (_decay_) du _edge_ en fonction du temps passé
depuis sa création. En somme, le score d’un _edge_ peut être calculé grâce à
la formule suivante : Σ UeWeDe ; plus le score est élevé, plus l’action prise
par l’utilisateur-acteur a des chances d’apparaître sur le fil d’actualité de
l’utilisateur-lecteur. Cependant, le terme d’EdgeRank est aujourd’hui
tombé en désuétude : devant la massification des usages, la
commercialisation croissante du réseau et la multiplication des appareils
mobiles, ces trois variables ont été submergées par près de 100 000 facteurs
de poids (types de publication, personnalisation des paramètres par
l’utilisateur, publicités, appareils utilisés, vitesse de connexion, etc.).
|===
