
:experimental:
:lang: fr

:toc-title: Table des matières

= III / La légitimation des contenus

toc::[]

[.text-justify]

== Les modèles « classiques »
=== La reconnaissance symbolique de l’édition papier

video::AcF9ORS-rho[youtube]


De quelle manière peut-on donner de la crédibilité à un contenu ? Comment faire
en sorte qu’un texte, un document, une information soient considérés comme fiables ?
Comment donner de l’autorité à des affirmations ou à des idées ? Voici quelques unes des
questions fondamentales auxquelles doit répondre aujourd’hui la fonction éditoriale.
Comme on l’a vu, les maisons d’édition comptent, au moins depuis le XVIIIe siècle,
parmi les instances qui remplissent la fonction de légitimation. La légitimité du contenu
est fonction de la légitimité symbolique de la maison d’édition qui le publie. Mais
comment une maison d’édition peut-elle concrètement être source de légitimation ? Pour
répondre à cette question, on peut identifier trois différents types de légitimation : le
prestige, la visibilité et l’évaluation scientifique.

1. Le prestige dépend de la réputation qu’une maison d’édition a pu acquérir auprès
des lecteurs. Ces derniers connaissent le nom de la maison et associent à ce nom une
idée de qualité. Cette valeur symbolique est transférée de la maison d’édition aux
ouvrages qu’elle publie. Concrètement, le nom et le logo de la maison confèrent du
prestige à l’ouvrage et garantissent sa qualité. Ce type de légitimation est typique
des contenus destinés au grand public.
2. La visibilité dépend de la capacité à faire connaître l’existence d’un contenu à un
certain nombre de personnes. Les maisons d’édition ont la possibilité de
communiquer sur leurs publications et de les rendre visibles. Si cette visibilité ne
garantit pas nécessairement la qualité de l’ouvrage, elle participe tout de même de sa
légitimation, car elle en détermine l’influence. Dans cette production de visibilité,
plusieurs maillons de la chaîne de valorisation du livre peuvent jouer un rôle
fondamental, comme les prix littéraires, qui augmentent l’audience des ouvrages et
se présentent comme un gage de qualité.
3. L’évaluation scientifique concerne seulement un type particulier de contenus : ceux
destinés à un public de spécialistes – notamment d’universitaires –, souvent publiés
par des maisons d’édition spécialisées – comme des presses universitaires – ou dans
des collections particulières. Chaque ouvrage est en général soumis, avant
publication, à un processus d’évaluation par les pairs : la qualité et la rigueur
scientifique du contenu sont analysés et appréciés, souvent en aveugle, par des
spécialistes. Ce processus garantit la légitimité de l’ouvrage. Dans ce cas, la maison
d’édition est le garant du bon déroulement du processus d’évaluation, les spécialistes
auxquels est demandée l’évaluation étant extérieurs à la maison.

Un contenu peut bénéficier de ces trois types de légitimation en même temps : avoir
du prestige, de la visibilité et être garanti par une évaluation scientifique. Souvent, ces
aspects sont liés : la visibilité peut dépendre du prestige, le prestige du sérieux de
l’évaluation scientifique, etc. Mais ces types de légitimation peuvent aussi jouer de
manière isolée : on peut prendre l’exemple d’une petite maison d’édition universitaire, à
la visibilité très réduite et au prestige parfois limité, ou d’une grande maison d’édition
commerciale, se donnant les ventes pour seul objectif, et misant tout sur la visibilité.
Les environnements numériques ont indéniablement produit de nouveaux modèles
de légitimation. Ils ont ainsi, en partie, remis en question le monopole que les maisons
d’édition avaient conservé pendant plusieurs siècles en matière de légitimation. Mais il
serait faux d’affirmer que le numérique a enlevé – ou même affaibli – le pouvoir de
légitimation et la valeur symbolique des maisons d’édition. Le fait d’être édité par l’une
d’entre elles – en papier ou en format numérique – reste la source principale de légitimité
pour un contenu, même si ce n’est plus la seule.
